#!/bin/bash

# Script to pull an updated version of the files for this course from
# a Subversion repository onto publically available space on AFS
# (accessible by student from AFS or via http).
#
# Optional first argument to script is used for specifying different HOST
# for the transfer

#HOST=clifton@clive.cs.rose-hulman.edu
#HOST=addiator.rose-hulman.edu
#HOST=sliderule.csse.rose-hulman.edu
HOST=addiator.rose-hulman.edu
if [ "${1}" != "" ] ; then
	HOST="${1}"
fi

# The directory on the remote host where the checked-out copy of the
# Public portion of the repository resides.
TARGDIR=/class/csse/catapult/2018-S1

# The local subdirectory which corresponds to the Public portion of the
# repository.
PUBLIC=`dirname ${0}`/Public

if [ -n "`svn st \"${PUBLIC}\"`" ] ; then
	echo "Uncommitted changes in ${PUBLIC}"
	echo "Commit changes before publishing"
	exit 1
fi

ssh ${HOST} "svn up \"${TARGDIR}\""

