SHELL = /bin/bash

# Just some commands to allow you to demo the jekyll site locally
# 
# all the relevant details are here:
# https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll

# this needs to be run to download the neccessary gems
# should be only needed once
install:
	bundle install

# this is the actual command you need to to start the preview
demo:
	bundle exec jekyll serve --watch                                

